//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant
    {
        public int Id { get; set; }
        public System.Guid UserId { get; set; }
        public Nullable<bool> IsReal { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Company { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<byte> DegreeId { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string NationalCode { get; set; }
        public string PresenterCompany { get; set; }
        public byte[] Image { get; set; }
        public string ZipCode { get; set; }
        public bool IsPresentation { get; set; }
        public bool IsWebSite { get; set; }
    
        public virtual User User { get; set; }
    }
}
