//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionHandler
    {
        public string Title { get; set; }
        public string HelpNote { get; set; }
        public string Message { get; set; }
        public string InnerException { get; set; }
        public byte Code { get; set; }
    }
}
